import { Link } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { Bot, Brain, CheckCircle2, ClipboardList, Globe2, MessageCircle, Play, Send, Sparkles, Users, Workflow, Zap } from "lucide-react";
import { AppSettings } from "@/types/types";
import { CheckList, FaqBlock, RevenueCta } from "./featureShared";

const compare = ["Agentic understanding", "Goal based actions", "Context memory", "Human handoff", "Tool and API actions", "Multilingual conversations"];
const steps = ["Create your AI agent", "Train your AI agent with content and tools", "Choose your AI skills", "Define custom goal", "Train your AI with your business knowledge", "Test conversations and fine tune responses", "Publish your AI agent on WhatsApp"];
const how = ["Your AI trains on your business", "Your AI gets work done", "Your AI assists the team", "Every message finds the right answer"];
const agentTypes = ["Customer support agent", "Sales and lead qualification", "Appointment booking agent", "FAQ and knowledge base agent", "Order status lookup agent", "Custom AI agents"];
const faqs = ["What is WhatsApp AI Agent?", "How is this different from a regular chatbot?", "How does an AI agent on WhatsApp work?", "What are the benefits of integrating a WhatsApp AI Agent with WhatsApp Business API?", "Can the AI agent send hyper-personalized messages?", "Which industries benefit most from AI customer support on WhatsApp?", "Can WhatsApp AI Agents replace human agents completely?", "What features should I look for in a WhatsApp AI assistant?", "What are AI messages and how do they work?", "Do I get free messages to test before going live?", "What languages does the AI agent support?", "Do I need a developer to set this up?", "Can the AI agent send images or media?"];

export default function FeaturesWhatsappAiAgentsPage() {
  const { data: settings } = useQuery<AppSettings>({ queryKey: ["/api/brand-settings"], staleTime: 1000 * 60 * 5 });
  const appName = settings?.title || "WhatsWay";
  return (
    <main className="bg-white text-slate-950">
      <section className="border-b border-emerald-100 bg-gradient-to-b from-emerald-50/70 to-white px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.9fr_1fr] lg:items-center"><div><p className="text-sm font-black uppercase text-green-600">Feature</p><h1 className="mt-3 max-w-2xl text-4xl font-black leading-tight sm:text-5xl">Build Smart <span className="text-green-500">WhatsApp AI Agents</span> with {appName}</h1><p className="mt-5 text-lg leading-8 text-slate-600">Train AI agents to understand your business, answer customers, automate work, and hand off to your team when needed.</p><div className="mt-7 flex gap-3"><Link href="/auth/register" className="rounded-md bg-green-500 px-5 py-3 text-sm font-black text-white">Start for FREE</Link><Link href="/book-demo" className="rounded-md border border-slate-300 px-5 py-3 text-sm font-black">Book a Demo</Link></div></div><div className="rounded-2xl bg-green-50 p-5"><div className="rounded-xl bg-white p-5 shadow-xl"><Bot className="h-16 w-16 text-green-500" /><div className="mt-5 space-y-3">{["Understand", "Decide", "Reply", "Live chat"].map((x) => <div key={x} className="rounded-md bg-emerald-50 p-3 font-bold">{x}</div>)}</div></div></div></div></section>
      <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-2 lg:items-center"><div className="rounded-2xl bg-slate-50 p-5"><div className="h-96 rounded-xl bg-white shadow-inner" /></div><div><h2 className="text-3xl font-black">What is an <span className="text-green-500">AI Agent</span> on WhatsApp?</h2><p className="mt-4 text-lg leading-8 text-slate-600">An AI Agent is a trained assistant that can understand messages, use your business data, and complete actions like lead capture, support, follow-ups, and handoffs.</p><CheckList items={["24/7 replies", "Context-aware responses", "Human handoff", "Business tool actions"]} /></div></div></section>
      <section className="bg-emerald-50 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl text-center"><h2 className="text-3xl font-black">Watch How <span className="text-green-500">AI Agents</span> Work</h2><div className="mt-8 flex aspect-video items-center justify-center rounded-2xl bg-green-200"><Play className="h-16 w-16 text-green-700" /></div></div></section>
      <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><h2 className="text-center text-2xl font-black sm:text-3xl">AI Agent vs <span className="text-green-500">Basic Keyword Chatbot</span></h2><div className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{compare.map((item) => <div key={item} className="rounded-md border border-slate-100 p-5 shadow-sm"><CheckCircle2 className="h-6 w-6 text-green-500" /><h3 className="mt-4 font-black">{item}</h3><p className="mt-2 text-sm text-slate-600">AI agents go beyond fixed keyword responses and understand customer intent.</p></div>)}</div></div></section>
      <section className="bg-slate-50 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><h2 className="text-center text-2xl font-black sm:text-3xl">Build your first agent in <span className="text-green-500">5 simple steps</span></h2><div className="mt-10 grid gap-6 md:grid-cols-2">{steps.map((step, index) => <div key={step} className="rounded-md bg-white p-6 shadow-sm"><p className="text-5xl font-black text-slate-100">#{index + 1}</p><h3 className="-mt-5 font-black">{step}</h3><p className="mt-2 text-sm leading-6 text-slate-600">Complete this stage in the {appName} dashboard and test your WhatsApp AI agent.</p><div className="mt-4 h-28 rounded-xl bg-emerald-50" /></div>)}</div></div></section>
      <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><h2 className="text-center text-2xl font-black sm:text-3xl">How WhatsApp AI Agents Work</h2><div className="mt-8 grid gap-6 md:grid-cols-2">{how.map((item) => <div key={item} className="rounded-md border border-slate-100 p-6 shadow-sm"><Brain className="h-8 w-8 text-green-500" /><h3 className="mt-4 font-black">{item}</h3><p className="mt-2 text-sm leading-6 text-slate-600">The agent uses your knowledge, tools, and instructions to respond accurately.</p><Link href="/auth/register" className="mt-4 inline-flex rounded-md bg-green-500 px-3 py-2 text-xs font-black text-white">Learn More</Link></div>)}</div></div></section>
      <section className="bg-slate-50 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-center text-2xl font-black sm:text-3xl">Types of AI Agents You Can Build</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{agentTypes.map((type) => <div key={type} className="rounded-md bg-white p-5 shadow-sm"><Sparkles className="h-7 w-7 text-green-500" /><h3 className="mt-4 font-black">{type}</h3><p className="mt-2 text-sm text-slate-600">Launch this agent with your own business knowledge and workflows.</p></div>)}</div></div></section>
      <section className="bg-lime-100 px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="text-2xl font-black">Build WhatsApp AI Agents easily</h2><p className="mt-2 text-slate-700">Start with an affordable AI agent builder and scale as your use case grows.</p></div><div className="rounded-md bg-white px-6 py-4 shadow-sm"><p className="text-sm font-bold text-slate-500">Starting from</p><p className="text-3xl font-black">Rs. 3,500</p></div><Link href="/auth/register" className="rounded-md bg-green-500 px-5 py-3 text-sm font-black text-white">Start for FREE</Link></div></section>
      <FaqBlock questions={faqs} appName={appName} />
    </main>
  );
}

