import { Link } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight, Bot, CalendarCheck, CheckCircle2, ClipboardList, FileText, Globe2, GraduationCap, Headphones, Home, MessageCircle, MousePointer2, PackageCheck, ReceiptText, Send, ShieldCheck, ShoppingCart, Sparkles, Ticket, Users } from "lucide-react";
import { AppSettings } from "@/types/types";

const logos = ["Skullcandy", "Quikr", "PhysicsWallah", "HDFC", "HomeLane", "IndiaMART", "Gameskraft"];
const useCases = [
  { title: "Streamline lead qualification and data collection", text: "Guide users through a designed form to qualify leads and capture contact information.", points: ["Ask questions conversationally", "Collect name, number, requirement, and intent", "Send data directly to your team"] },
  { title: "Engage tenants and gather feedback directly within WhatsApp", text: "Use forms to collect survey answers, feedback, and preferences without sending users outside WhatsApp.", points: ["Create short surveys", "Collect feedback instantly", "Improve response rates"] },
  { title: "Seamlessly process loan applications", text: "Offer a smooth loan or application experience with guided WhatsApp forms.", points: ["Display pre-approved loan amounts", "Collect applicant information", "Attach docs and verify details"] },
  { title: "Simplify insurance sales", text: "Use WhatsApp forms to capture plan interest, nominee details, and customer requirements.", points: ["Collect preferences", "Capture details", "Trigger policy follow-up"] },
  { title: "Collect purchase intent", text: "Understand what customers want by using WhatsApp forms to collect interest and purchase information.", points: ["Collect product interest", "Record purchase timeline", "Retarget warm customers"] },
  { title: "Drive conversions with personalized offers", text: "Use form data to personalize offers and recommend relevant services.", points: ["Segment users", "Send relevant offers", "Boost conversion"] },
];
const formCases = ["Placing Orders", "Event Registration", "Booking Appointments", "Restaurant Reservations", "Gathering Client Feedback", "Quotation Request", "General Contact Form", "Travel Booking"];
const stories = [["COSCO", "Sports Equipment Brand"], ["give", "Donation Collection Platform"], ["Edtech Platform", "Education Platform"]];
const engagement = [
  { icon: Headphones, title: "Multiple human live chat" }, { icon: Bot, title: "Chatbot flow builder" }, { icon: Users, title: "Retarget users on WhatsApp" }, { icon: Send, title: "WhatsApp scheduler" },
  { icon: ClipboardList, title: "Import, broadcast and track" }, { icon: MousePointer2, title: "Ads that click to WhatsApp" }, { icon: Globe2, title: "WhatsApp webviews" }, { icon: FileText, title: "WhatsApp forms" },
];
const faqs = ["What are WhatsApp Forms?", "How do WhatsApp Forms work?", "What can WhatsApp Forms be used for?", "Are WhatsApp Forms better than traditional website forms?", "Can I use WhatsApp Forms for lead generation?", "Can I use WhatsApp Forms for appointment booking?", "Do WhatsApp Forms support coding?", "Can WhatsApp Forms be integrated with a CRM or other software?", "Can WhatsApp Forms be used with Click to WhatsApp Ads?"];

export default function FeaturesWhatsappFormsPage() {
  const { data: settings } = useQuery<AppSettings>({ queryKey: ["/api/brand-settings"], staleTime: 1000 * 60 * 5 });
  const appName = settings?.title || "WhatsWay";

  return (
    <main className="bg-white text-slate-950">
      <section className="border-b border-emerald-100 bg-gradient-to-b from-emerald-50/60 to-white px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.95fr_1fr] lg:items-center">
          <div><p className="text-sm font-black uppercase text-green-600">Feature</p><h1 className="mt-3 max-w-2xl text-4xl font-black leading-tight sm:text-5xl">Collect Data Seamlessly with <span className="text-green-500">WhatsApp Forms</span></h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">Enhance user engagement with forms that open directly within WhatsApp. Capture leads, qualify users, book orders, and move using WhatsApp Forms.</p><p className="mt-3 font-bold text-green-600">Powered by Official WhatsApp Business API</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/auth/register" className="rounded-md bg-green-500 px-5 py-3 text-sm font-black text-white">Start for FREE</Link><Link href="/book-demo" className="rounded-md border border-slate-300 px-5 py-3 text-sm font-black">Talk to Sales</Link></div></div>
          <div className="rounded-[2rem] bg-emerald-50 p-5"><div className="relative min-h-[360px] rounded-2xl bg-white p-6 shadow-xl"><div className="mx-auto h-72 w-44 rounded-[2rem] bg-slate-950 p-3"><div className="h-full rounded-[1.5rem] bg-green-50 p-3"><p className="rounded-lg bg-white p-3 text-sm font-bold">Lead Form</p><div className="mt-3 space-y-2">{["Name", "Phone", "Requirement", "Budget"].map((field) => <div key={field} className="rounded-md bg-white p-2 text-xs font-bold text-slate-500">{field}</div>)}</div><p className="mt-3 rounded-lg bg-green-500 p-2 text-center text-xs font-black text-white">Submit</p></div></div><div className="absolute left-8 top-8 rounded-xl bg-white p-4 shadow"><p className="font-black">New form response</p><p className="text-sm text-green-600">Lead qualified</p></div><div className="absolute bottom-8 right-8 rounded-xl bg-green-50 p-4 shadow"><CheckCircle2 className="h-8 w-8 text-green-500" /></div></div></div>
        </div>
      </section>

      <section className="px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl text-center"><h2 className="text-2xl font-black">Founders & Marketers Love us</h2><p className="mt-2 text-sm text-slate-500">Trusted by 210,000+ businesses across 68+ countries</p><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{logos.map((logo) => <div key={logo} className="rounded-md border border-slate-100 px-3 py-3 text-sm font-black text-slate-500 shadow-sm">{logo}</div>)}</div></div></section>

      <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[1fr_0.85fr] lg:items-center"><div><h2 className="text-3xl font-black">What are WhatsApp Forms?</h2><p className="mt-4 text-lg leading-8 text-slate-600">WhatsApp Forms are in-channel forms where users can offer responses, make choices, and share details without leaving WhatsApp. They are ideal for surveys, bookings, lead capture, and purchase intent.</p><div className="mt-6 space-y-4"><div className="flex gap-3"><ReceiptText className="h-6 w-6 text-green-500" /><div><h3 className="font-black">Native experience</h3><p className="text-sm text-slate-600">Collect structured answers inside WhatsApp.</p></div></div><div className="flex gap-3"><ShieldCheck className="h-6 w-6 text-green-500" /><div><h3 className="font-black">Customizable</h3><p className="text-sm text-slate-600">Design forms relevant to your business needs.</p></div></div></div><Link href="/auth/register" className="mt-6 inline-flex rounded-md bg-green-500 px-4 py-2 text-sm font-black text-white">Learn More</Link></div><div className="grid grid-cols-2 gap-4"><div className="h-80 rounded-[2rem] bg-slate-950 p-3"><div className="h-full rounded-[1.5rem] bg-green-50 p-3" /></div><div className="mt-10 h-80 rounded-[2rem] bg-slate-950 p-3"><div className="h-full rounded-[1.5rem] bg-white p-3" /></div></div></div></section>

      <section className="bg-white px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-center text-2xl font-black sm:text-3xl">WhatsApp Forms Unique Use Cases</h2><p className="mx-auto mt-3 max-w-3xl text-center text-slate-600">Check out multiple ways you can use WhatsApp Forms for your business.</p><div className="mt-12 space-y-14">{useCases.map((item, index) => <div key={item.title} className="grid gap-8 lg:grid-cols-2 lg:items-center"><div className={index % 2 ? "lg:order-2" : ""}><p className="text-5xl font-black text-slate-100">#{index + 1}</p><h3 className="-mt-5 text-xl font-black">{item.title}</h3><p className="mt-3 leading-7 text-slate-600">{item.text}</p><div className="mt-4 space-y-2">{item.points.map((point) => <div key={point} className="flex gap-2 text-sm font-bold text-slate-700"><CheckCircle2 className="h-4 w-4 text-green-500" />{point}</div>)}</div></div><div className="rounded-2xl bg-slate-50 p-5"><div className="grid grid-cols-3 gap-3">{[1, 2, 3].map((phone) => <div key={phone} className="h-64 rounded-[1.5rem] bg-slate-950 p-2"><div className="h-full rounded-[1.2rem] bg-white p-2"><div className="h-3 w-2/3 rounded-full bg-slate-200" /><div className="mt-3 space-y-2">{[1, 2, 3, 4].map((line) => <div key={line} className="h-5 rounded bg-green-50" />)}</div><div className="mt-4 h-7 rounded bg-green-500" /></div></div>)}</div></div></div>)}</div></div></section>

      <section className="bg-slate-50 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[0.75fr_1fr]"><div><h2 className="text-3xl font-black">WhatsApp Forms Use-Cases</h2><p className="mt-3 text-slate-600">Here is how you can effectively use WhatsApp lead generation forms for different scenarios.</p><Link href="/book-demo" className="mt-5 inline-flex rounded-md bg-green-500 px-4 py-2 text-sm font-black text-white">Talk to Sales</Link></div><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{formCases.map((item) => <div key={item} className="rounded-md bg-white p-5 shadow-sm"><ClipboardList className="h-6 w-6 text-green-500" /><h3 className="mt-4 font-black">{item}</h3><p className="mt-2 text-sm text-slate-600">Collect details, preferences, and requirements using WhatsApp Forms.</p></div>)}</div></div></section>

      <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-3xl font-black">How Brands use {appName} for WhatsApp Marketing</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{stories.map(([brand, type]) => <div key={brand} className="rounded-md border border-slate-100 bg-white p-6 shadow-sm"><h3 className="text-2xl font-black text-red-500">{brand}</h3><p className="mt-5 font-black">{type}</p><p className="mt-2 text-sm leading-6 text-slate-600">Used WhatsApp journeys and forms to improve customer engagement.</p><Link href="/resources/case-studies" className="mt-5 inline-flex rounded-md border border-slate-300 px-4 py-2 text-sm font-black">Explore Case Study <ArrowRight className="ml-2 h-4 w-4" /></Link></div>)}</div></div></section>

      <section className="bg-slate-50 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-center text-2xl font-black sm:text-3xl">Everything You Need for WhatsApp Engagement</h2><p className="mt-2 text-center text-slate-600">Marketing, CRM and customer support in one place.</p><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{engagement.map(({ icon: Icon, title }) => <div key={title} className="rounded-md border border-slate-100 bg-white p-5 shadow-sm"><Icon className="h-7 w-7 text-green-500" /><h3 className="mt-4 font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-600">Use this feature with forms to capture and convert more leads.</p><Link href="/auth/register" className="mt-4 inline-flex rounded-md bg-green-500 px-3 py-2 text-xs font-black text-white">Learn More</Link></div>)}</div></div></section>

      <section className="bg-lime-100 px-4 py-9 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="text-3xl font-black">Drive 3x Revenue with {appName}</h2><p className="mt-2 text-slate-700">Get started for FREE. No credit card needed.</p></div><div className="flex gap-3"><Link href="/auth/register" className="rounded-md bg-green-500 px-5 py-3 text-sm font-black text-white">Start for FREE</Link><Link href="/book-demo" className="rounded-md border border-slate-900 px-5 py-3 text-sm font-black">Talk to Sales</Link></div></div></section>

      <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><h2 className="text-2xl font-black">FAQ</h2><p className="mt-2 text-sm text-slate-500">Frequently asked questions about WhatsApp Forms</p><div className="mt-6 divide-y divide-slate-100 rounded-md border border-slate-100 bg-white">{faqs.map((faq) => <details key={faq} className="p-5"><summary className="cursor-pointer list-none font-bold">{faq}</summary><p className="mt-3 text-sm leading-6 text-slate-600">Yes. {appName} supports WhatsApp Form workflows for lead capture, surveys, booking, and data collection.</p></details>)}</div></div></section>
    </main>
  );
}

