import { Link } from "wouter";
import { useQuery } from "@tanstack/react-query";
import { ArrowRight, BadgeCheck, Bot, Brain, CheckCircle2, ClipboardList, Globe2, Languages, MessageCircle, Mic, PhoneCall, Play, ShieldCheck, Sparkles, Star, Users, Zap } from "lucide-react";
import { AppSettings } from "@/types/types";

const logos = ["Lenskart", "Quikr", "The Man Co", "HDFC", "Reliance", "Edelweiss", "Apollo"];
const comparison = [
  ["Intelligence", "Learns from interactions and context", "Agent-led understanding", "Rule-based responses"],
  ["Speed", "Instant replies 24x7", "Depends on availability", "Fast but limited"],
  ["Scalability", "Handles thousands of chats", "Limited by team size", "Scales with basic scripts"],
  ["Availability", "Always active", "Business hours", "Active if configured"],
  ["Personalization", "Dynamic answers and recommendations", "Manual personalization", "Static replies"],
];
const botTypes = ["Text to Text", "Text to Voice", "Voice to Text", "Voice to Voice", "Image Response", "Video Response"];
const scaleCards = ["Effortless appointment scheduling", "Automated financial tasks", "Smart feedback collection", "Product recommendations", "Lead qualification", "Support escalation"];
const examples = [
  { title: "AI WhatsApp Chatbot for the UN World Heritage", text: "Guide travelers through sites, languages, routes, and information with a conversational assistant." },
  { title: "KrishiAI: Revolutionizing Agriculture with AI", text: "Help farmers access crop guidance, weather insights, and market updates over WhatsApp." },
  { title: "How Sunfeast Dark Fantasy Uses AI WhatsApp Chatbot", text: "Create a branded campaign experience with product discovery and interactive flows." },
];
const faqs = ["What is the difference between an AI WhatsApp chatbot and a regular WhatsApp chatbot?", "Is WhatsApp chatbot built on the official WhatsApp Business API?", "Can I integrate the AI WhatsApp chatbot with my CRM?", "Can I hand over conversations from the AI chatbot to a human agent?", "Can WhatsApp AI agents analyze human queries?", "How much does it cost to set up an AI WhatsApp chatbot?", "How do I train the AI WhatsApp chatbot for my business?", "Can the chatbot send rich messages like buttons, lists, images, and documents?"];

export default function ProductAiWhatsappChatbotPage() {
  const { data: settings } = useQuery<AppSettings>({ queryKey: ["/api/brand-settings"], staleTime: 1000 * 60 * 5 });
  const appName = settings?.title || "WhatsWay";

  return (
    <main className="bg-white text-slate-950">
      <section className="border-b border-emerald-100 bg-gradient-to-br from-emerald-50 via-white to-emerald-50 px-4 py-16 sm:px-6 lg:px-8">
        <div className="mx-auto grid max-w-7xl gap-10 lg:grid-cols-[1fr_0.85fr] lg:items-center">
          <div><p className="text-sm font-black uppercase text-green-600">AI-powered product</p><h1 className="mt-3 max-w-2xl text-4xl font-black leading-tight sm:text-5xl"><span className="text-green-500">AI WhatsApp Chatbot:</span> Supercharge Your Customer Experience</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">Deploy intelligent AI assistants that understand customer queries, reply naturally, and guide users across support, sales, bookings, and transactions.</p><div className="mt-7 flex flex-wrap gap-3"><Link href="/auth/register" className="rounded-md bg-green-500 px-5 py-3 text-sm font-black text-white">Request Callback</Link><Link href="/book-demo" className="rounded-md border border-slate-300 px-5 py-3 text-sm font-black">Learn More</Link></div></div>
          <div className="rounded-[2rem] bg-green-100 p-5 shadow-xl shadow-emerald-100"><div className="grid gap-4 rounded-2xl bg-white p-5 md:grid-cols-[180px_1fr]"><div className="rounded-[1.5rem] bg-slate-950 p-3"><div className="h-80 rounded-[1.2rem] bg-green-50 p-3"><p className="rounded-lg bg-white p-3 text-sm font-bold">Can you help me choose a plan?</p><p className="ml-auto mt-3 rounded-lg bg-green-500 p-3 text-sm font-bold text-white">Yes, tell me your team size.</p></div></div><div className="space-y-3 self-center">{["Lead statement", "Loan eligibility", "Product card", "More"].map((item) => <div key={item} className="rounded-md border border-green-100 bg-green-50 p-3 text-sm font-black text-green-700">{item}</div>)}</div></div></div>
        </div>
      </section>

      <section className="px-4 py-12 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl text-center"><h2 className="text-2xl font-black">Founders & Marketers Love us</h2><div className="mt-7 grid grid-cols-2 gap-3 sm:grid-cols-4 lg:grid-cols-7">{logos.map((logo) => <div key={logo} className="rounded-md border border-slate-100 px-3 py-3 text-sm font-black text-slate-500 shadow-sm">{logo}</div>)}</div></div></section>

      <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto grid max-w-6xl gap-10 lg:grid-cols-[0.9fr_1fr] lg:items-center"><div className="rounded-2xl bg-emerald-50 p-5"><div className="rounded-xl bg-white p-5 shadow-xl"><MessageCircle className="h-12 w-12 text-green-500" /><div className="mt-5 space-y-3">{["Understand intent", "Answer in context", "Recommend next action"].map((item) => <div key={item} className="rounded-md bg-slate-50 p-3 font-bold">{item}</div>)}</div></div></div><div><h2 className="text-3xl font-black">What is an AI WhatsApp Chatbot?</h2><p className="mt-4 text-lg leading-8 text-slate-600">Imagine an AI agent available 24x7 on WhatsApp, providing human-like customer support without wait time. It uses your business knowledge to answer questions and move users toward the next action.</p><div className="mt-6 grid gap-3">{["Multi-language support", "Supports text, voice, image, and video", "Integrates with payments, CRMs, and backend systems"].map((point) => <div key={point} className="flex items-center gap-3"><CheckCircle2 className="h-5 w-5 text-green-500" /><span className="font-bold text-slate-700">{point}</span></div>)}</div></div></div></section>

      <section className="bg-slate-50 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl"><h2 className="text-center text-2xl font-black sm:text-3xl">Comparison Table</h2><div className="mt-8 overflow-hidden rounded-md border border-slate-200 bg-white"><table className="w-full min-w-[720px] text-left text-sm"><thead className="bg-slate-950 text-white"><tr><th className="p-4">Parameter</th><th className="p-4">AI WhatsApp Chatbot</th><th className="p-4">Human Agent</th><th className="p-4">Traditional Chatbot</th></tr></thead><tbody>{comparison.map((row) => <tr key={row[0]} className="border-t border-slate-100"><td className="p-4 font-black">{row[0]}</td><td className="p-4 text-slate-600">{row[1]}</td><td className="p-4 text-slate-600">{row[2]}</td><td className="p-4 text-slate-600">{row[3]}</td></tr>)}</tbody></table></div></div></section>

      <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-center text-2xl font-black sm:text-3xl">Types of AI WhatsApp Chatbots You Can Deploy with {appName}</h2><div className="mt-8 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{botTypes.map((type, index) => <div key={type} className="rounded-md border border-slate-100 bg-white p-5 text-center shadow-sm">{[Bot, Mic, MessageCircle, PhoneCall, Sparkles, Play].map((Icon, i) => i === index ? <Icon key={i} className="mx-auto h-8 w-8 text-green-500" /> : null)}<h3 className="mt-4 font-black">{type}</h3><p className="mt-2 text-sm text-slate-600">Create intelligent conversations for this interaction format.</p></div>)}</div></div></section>

      <section className="bg-slate-50 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-center text-2xl font-black sm:text-3xl">Built for Businesses That Want to Scale</h2><p className="mx-auto mt-3 max-w-3xl text-center text-slate-600">No matter your industry, AI assistants help teams reduce repetitive work and improve customer response speed.</p><div className="mt-8 grid gap-5 md:grid-cols-3">{scaleCards.map((card) => <div key={card} className="rounded-md border border-slate-100 bg-white p-5 shadow-sm"><Brain className="h-7 w-7 text-green-500" /><h3 className="mt-4 font-black">{card}</h3><p className="mt-2 text-sm leading-6 text-slate-600">Automate repetitive conversations while keeping human takeover available.</p></div>)}</div></div></section>

      <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><h2 className="text-center text-2xl font-black sm:text-3xl">Deploy Your Own AI WhatsApp Chatbot with {appName}</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{["Build it yourself and integrate with {appName}", "Let us build it for you"].map((title) => <div key={title} className="rounded-md border border-slate-100 p-6 shadow-sm"><BadgeCheck className="h-8 w-8 text-green-500" /><h3 className="mt-4 font-black">{title.replace("{appName}", appName)}</h3><p className="mt-2 text-sm leading-6 text-slate-600">Choose the setup path that fits your team and launch an AI assistant faster.</p><Link href="/book-demo" className="mt-4 inline-flex rounded-md bg-green-500 px-4 py-2 text-sm font-black text-white">Request Callback</Link></div>)}</div></div></section>

      <section className="bg-emerald-50 px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-6xl space-y-10">{examples.map((example, index) => <div key={example.title} className="grid gap-8 rounded-md bg-white p-6 shadow-sm lg:grid-cols-[1fr_0.8fr] lg:items-center"><div><p className="text-sm font-black uppercase text-green-600">Real-world example</p><h2 className="mt-2 text-2xl font-black">{example.title}</h2><p className="mt-3 leading-7 text-slate-600">{example.text}</p><div className="mt-5 space-y-2">{["Smart multi-agent assistant", "Voice and text recognition", "Deep consultation"].map((point) => <div key={point} className="flex items-center gap-2 text-sm font-bold"><CheckCircle2 className="h-4 w-4 text-green-500" />{point}</div>)}</div></div><div className="rounded-2xl bg-slate-50 p-5"><div className="aspect-video rounded-xl bg-white shadow-inner" /><p className="mt-3 text-center text-sm font-black text-slate-500">Example {index + 1}</p></div></div>)}</div></section>

      <section className="px-4 py-16 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl text-center"><h2 className="text-2xl font-black sm:text-3xl">How Ankur Warikoo uses {appName}</h2><p className="mx-auto mt-3 max-w-3xl text-slate-600">A video-style customer story block for showcasing AI automation and WhatsApp engagement.</p><div className="mt-8 flex aspect-video items-center justify-center rounded-2xl bg-slate-950 text-white"><Play className="h-16 w-16" /></div></div></section>

      <section className="bg-lime-100 px-4 py-10 sm:px-6 lg:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h2 className="text-2xl font-black">Ready to Build Your AI Success Story?</h2><p className="mt-2 text-slate-700">AI does not replace teams. It helps them respond faster and sell smarter.</p></div><div className="flex gap-3"><Link href="/book-demo" className="rounded-md bg-green-500 px-5 py-3 text-sm font-black text-white">Request Callback</Link><Link href="/auth/register" className="rounded-md border border-slate-900 px-5 py-3 text-sm font-black">Learn More</Link></div></div></section>

      <section className="px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-5xl"><h2 className="text-2xl font-black">FAQ</h2><div className="mt-6 divide-y divide-slate-100 rounded-md border border-slate-100 bg-white">{faqs.map((faq) => <details key={faq} className="p-5"><summary className="cursor-pointer list-none font-bold">{faq}</summary><p className="mt-3 text-sm leading-6 text-slate-600">Yes. {appName} can support this workflow with the right WhatsApp Business API setup.</p></details>)}</div></div></section>
    </main>
  );
}

